export enum PrimaryKeys {
  ddv_users = 'user_id',
  ddv_users_auth_external = 'user_id',
  ddv_user_profiles = 'user_id',
  ddv_banners = 'banner_id',
  ddv_banner_images = 'banner_id',
  ddv_banner_descriptions = 'banner_id',
  ddv_images = 'image_id',
  ddv_images_links = 'image_id',
  ddv_categories = 'category_id',
  ddv_category_descriptions = 'category_id',
  ddv_category_vendor_product_count = 'category_id',
  ddv_statuses = 'status_id',
  ddv_status_descriptions = 'status_id',
  ddv_status_data = 'status_id',
  ddv_payment_descriptions = 'payment_id',
  ddv_payments = 'payment_id',
}
