export enum Table {
  USERS = 'ddv_users',
  PRODUCTS = 'products',
  CATEGORIES = 'categories',
  USERS_AUTH = 'ddv_users_auth_external',
  USER_PROFILES = 'ddv_user_profiles',
  USER_GROUPS = 'ddv_usergroups',
  USER_GROUP_PRIVILEGES = 'ddv_usergroup_privileges',
  USER_GROUP_DESCRIPTIONS = 'ddv_usergroup_descriptions',
  USER_GROUP_LINKS = 'ddv_usergroup_links',
  BANNER = 'ddv_banners',
  BANNER_IMAGE = 'ddv_banner_images',
  BANNER_DESCRIPTIONS = 'ddv_banner_descriptions',
  IMAGE = 'ddv_images',
  IMAGE_LINK = 'ddv_images_links',
}
