export class User {
  user_id?: string;
  status: string;
  user_type: string;
  user_login: string;
  referer: string;
  is_root: string;
  company_id: number;
  last_login: number;
  timestamp: number;
  password: string;
  salt: string;
  firstname: string;
  lastname: string;
  company: string;
  email: string;
  phone: string;
  fax: string;
  url: string;
  tax_exempt: string;
  birthday: number;
  purchase_timestamp_from: number;
  purchase_timestamp_to: number;
  responsible_email: string;
  last_passwords: string;
  password_change_timestamp: number;
  api_key: string;
  janrain_identifier: string;
}
